name: AMV Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev

      - name: Download and build Linux kernel 6.15.3
        run: |
          curl -LO https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.15.3.tar.xz
          tar -xf linux-6.15.3.tar.xz
          cd linux-6.15.3
          make defconfig
          make -j$(nproc)
          cp arch/x86/boot/bzImage ../bzImage

      - name: Download and build BusyBox
        run: |
          curl -LO https://busybox.net/downloads/busybox-1.36.1.tar.bz2
          tar -xf busybox-1.36.1.tar.bz2
          cd busybox-1.36.1
          make defconfig
          make -j$(nproc)
          make install CONFIG_PREFIX=../rootfs

      - name: Prepare root filesystem
        run: |
          cd rootfs
          mkdir -p proc sys dev etc etc/init.d
          echo -e '#!/bin/sh\nmount -t proc proc /proc\nmount -t sysfs sys /sys\necho Welcome\n/bin/sh' > init
          chmod +x init

      - name: Create initramfs
        run: |
          cd rootfs
          find . | cpio -H newc -o | gzip > ../initramfs.img

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: minimal-linux
          path: |
            bzImage
            initramfs.img
